# docker-compose for n8n; DISCORD_WEBHOOK_URL is injected via the host shell/.env at compose runtime.
version: '3.8'
services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - ./data:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: America/Los_Angeles
      N8N_PERSONALIZATION_ENABLED: "false"
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
